name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main  # Trigger on push to main branch
      - test

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce -y
        sudo docker --version
        sudo systemctl enable docker
        sudo systemctl start docker
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Login to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY_FILE }}

    - name: Configure docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud --quiet auth configure-docker

    - name: Extract GCP project ID
      id: project
      run: echo "::set-output name=id::${{ secrets.GCP_PROJECT_ID }}"

    - name: Build and push Docker images to GCR
      run: |
        docker build -t devops-fullstack-app-backend:v1 -f backend/Dockerfile .
        docker build -t devops-fullstack-app-frontend:v1 -f frontend/Dockerfile .

        # Tag images for GCR
        docker tag devops-fullstack-app-frontend:v1 gcr.io/${{ secrets.GCP_PROJECT_ID }}/sarveshsd/devops-fullstack-app-frontend:v1
        docker tag devops-fullstack-app-backend:v1 gcr.io/${{ secrets.GCP_PROJECT_ID }}/sarveshsd/devops-fullstack-app-backend:v1

        # Push images to GCR
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sarveshsd/devops-fullstack-app-frontend:v1
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sarveshsd/devops-fullstack-app-backend:v1
        

