name: Deploy to GKE

on:
  push:
    branches:
      - main
      - test

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: semiotic-summer-423513-s2
      CLUSTER_NAME: tax-nandi-gke
      ZONE: us-central1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Setup gcloud auth
        run: |
          echo '${{ secrets.GCLOUD_AUTH }}' > gcloud-api-key.json
          gcloud auth activate-service-account --key-file=gcloud-api-key.json
          gcloud config set account subhanshu0027@gmail.com
      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{ env.ZONE }}-docker.pkg.dev

      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

    
      - name: Configure gcloud
        run: gcloud config set account subhanshu0027@gmail.com
      
      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      
      - name: Build and Submit Image
        id: build
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_URI=${{ env.ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/keycloak/keycloak:$TIMESTAMP
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          gcloud builds submit --region=${{ env.ZONE }} --tag $IMAGE_URI
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl
      - name: Authenticate kubectl with GKE
        env:
          PROJECT_ID: semiotic-summer-423513-s2
          ZONE: us-central1
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials tax-nandi-gke --zone $ZONE --project $PROJECT_ID
      - name: Update Kubernetes Deployment
        env:
          DEPLOYMENT_NAME: keycloak
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME keycloak=$IMAGE_URI`
